# Generated by Django 2.2.16 on 2022-04-02 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220402_0057'),
        ('reviews', '0002_auto_20220401_1701'),
    ]

    operations = [
    ]
