# Generated by Django 2.2.16 on 2022-04-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220402_2038'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='title',
            constraint=models.UniqueConstraint(fields=('name', 'year', 'category', 'genre'), name='unique_title'),
        ),
    ]
